[theme]
base = "light"
primaryColor = "#FF971C"  # Bright orange for primary actions
backgroundColor = "#FFF899"  # Light yellow for background
secondaryBackgroundColor = "#FFD36E"  # Soft orange for secondary backgrounds
textColor = "#005F99"  # Deep sky blue for text
font = "sans serif"
