# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#FF6347"  # Tomato
backgroundColor = "#FFFACD"  # LemonChiffon
secondaryBackgroundColor = "#F0E68C"  # Khaki
textColor = "#4B0082"  # Indigo
font = "sans serif"
