# .streamlit/config.toml


[theme]
base = "light"
primaryColor = "#e63946"  # Bright Red
backgroundColor = "#f1faee"  # Honeydew
secondaryBackgroundColor = "#a8dadc"  # Powder Blue
textColor = "#1d3557"  # Dark Blue
font = "sans serif"
